spring:
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://localhost:3306/spring
        username: root
        password: 8049
    servlet:
        multipart:
            max-file-size: 10GB
            max-request-size: 10GB
    mvc:
        async:
            request-timeout: 3600000
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update

jwt:
    secret: "thisisjwttokensecret"